replicas: 2

podLabels:
  test-label: test-label-value

podAnnotations:
  test-annotation: test-annotation-value-{{ .Release.Name }}
  test-int-annotation: "12345"

startupScripts:
  hello.sh: |
    #!/bin/sh

    echo '********************************************************************************'
    echo '*                                                                              *'
    echo '*                        Hello from my startup script!                         *'
    echo '*                                                                              *'
    echo '********************************************************************************'

lifecycleHooks: |
  postStart:
    exec:
      command:
        - /bin/sh
        - -c
        - echo 'Hello from lifecycle hook!'

extraEnv: |
  - name: KC_DB_USERNAME_FILE
    value: /secrets/admin-creds/user
  - name: KC_DB_PASSWORD_FILE
    value: /secrets/admin-creds/password
  - name: KC_METRICS_ENABLED
    value: "true"
  - name: KC_HTTP_RELATIVE_PATH
    value: "/auth"
  - name: KC_CACHE_STACK
    value: "kubernetes"
  - name: KC_HTTP_ENABLED
    value: "true"
  - name: JAVA_OPTS_APPEND
    value: >-
      -XX:+UseContainerSupport
      -XX:MaxRAMPercentage=50.0
      -Djava.net.preferIPv4Stack=true
      -Djava.awt.headless=true
      -Djgroups.dns.query={{ include "keycloak.serviceDnsName" . }}

secrets:
  admin-creds:
    stringData:
      user: admin
      password: secret

extraVolumeMounts: |
  - name: admin-creds
    mountPath: /secrets/admin-creds
    readOnly: true

extraVolumes: |
  - name: admin-creds
    secret:
      secretName: '{{ include "keycloak.fullname" . }}-admin-creds'

postgresql:
  enabled: true
  persistence:
    enabled: true

test:
  enabled: true
