apiVersion: v2
name: keycloakx
version: 1.0.0
appVersion: 17.0.0
description: Keycloak.X - Open Source Identity and Access Management For Modern Applications and Services
keywords:
  - sso
  - idm
  - openid connect
  - saml
  - kerberos
  - ldap
home: https://www.keycloak.org/
icon: https://www.keycloak.org/resources/images/keycloak_logo_480x108.png
sources:
  - https://github.com/codecentric/helm-charts
  - https://github.com/keycloak/keycloak-containers
  - https://github.com/bitnami/charts/tree/master/bitnami/postgresql
maintainers:
  - name: thomasdarimont
    email: thomas.darimont+github@gmail.com
dependencies:
  - name: postgresql
    version: 10.3.13
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
